logrotate_scripts:
  - name: NewsAlert
    path: "/home/deploy/narui/shared/log/*.log"
    options:
      - weekly
      - size 25M
      - missingok
      - compress
      - delaycompress
      - copytruncate
      - rotate 10
      - su deploy www-data
      - create 644 deply www-data
