---

- name: Prerequisites for provisioning (libcurl-dev)
  when: ansible_os_family == 'Debian'
  sudo: yes
  apt:
    name: "{{item}}"
  with_items:
    - python-pycurl  # Ansible's ppa module requires this
    - python-psycopg2  # Ansible's postgres modules require this
  tags:
    - postgresql
    - db
    - deps
